ENV["DB_NAME"] ||= "crystal_production"
ENV["DB_PASS"] ||= "test"
ENV["DB_PORT"] ||= "3306"
ENV["DB_SERVER"] ||= "database"
ENV["DB_TYPE"] ||= "mysql"
ENV["DB_USER"] ||= "root"
ENV["HOST"] ||= "0.0.0.0"
ENV["ENVIRONMENT"] ||= "dev"
ENV["APP_SECRET"] ||="30Cn/7TD/Ej/pD+PONU+lSdC5Frqm239xQ=="
