ENV["DB_NAME"] ||= "sirva_PROD"
ENV["DB_PASS"] ||= "M0veHQ12345"
ENV["DB_PORT"] ||= "3306"
ENV["DB_SERVER"] ||= "172.22.0.4"
ENV["DB_TYPE"] ||= "mysql"
ENV["DB_USER"] ||= "root"
ENV["HOST"] ||= "0.0.0.0"
ENV["ENVIRONMENT"] ||= "dev"
ENV["APP_SECRET"] ||="30Cn/7TD/Ej/pD+PONU+lSdC5Frqm239xQ=="
