version: "3.5"

networks:
    backend:
        name: crystal-backend

services:
    dev-crystallang:
        build:
            context: .
            dockerfile: DockerfileCrystal
            args:
                current_branch: master
                working_dir: /code/
        container_name: dev-crystallang
        ports:
            - "4000:4000"
        expose:
            - "4000"
        networks:
            - backend

    dev-database:
        restart: always
        build:
            context: .
            dockerfile: DockerfileDB
        container_name: dev-database
        environment:
            MYSQL_DATABASE: 'crystal_production'
            MYSQL_ROOT_PASSWORD: 'test'
            MYSQL_ROOT_HOST: '127.0.0.1'
        ports:
        - '3306:3306'
        expose:
        - '3306'
        networks:
            - backend
